### ISSUE TITLE
The SERP page doesn't show the form to make another search

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#101]
Currently the SERP (search engine results page, right after performing any search) looks like this:

![image](https://user-images.githubusercontent.com/794154/113569397-bda1b000-9612-11eb-9ee8-37d4e1037241.png)

It's unclear and/or impossible to perform another search to filter results.

**Desired Outcome**

It should be possible to continue searching from the SERP page.

Also note that:

-  the results overlap with the map, they shouldn't.
- some texts extend outside of their area, they shouldn't.

![image](https://user-images.githubusercontent.com/794154/113569567-05283c00-9613-11eb-8c9e-e74aa914c682.png)

**Comment by kanchan-bluebash** [comment]
`> It should be possible to continue searching from the SERP page.`

This issue has been fixed in  [#116](https://github.com/publicv-org/publicv/pull/116)
