### ISSUE TITLE
Adding a headshot doesn't work on iPhone

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#102]
I tried to create a new CV from the iPhone. 

![image](https://user-images.githubusercontent.com/794154/113569746-47517d80-9613-11eb-9c66-defdb73368bd.png)

In order to add my headshot I....
- clicked on the edit button
- clicked on "Upload Photo"
- selected Photo Library
- selected a picture of myself 
- clicked on confirm

Got no result.

**Desired Outcome**

It should be possible to upload a photo from the photo library of the users' phone.

**Comment by kanchan-bluebash** [comment]
This issue will be fixed with the pr #140

**Comment by darmenise** [comment]
@kanchan-bluebash please can you check with an iPhone if we can close this?

**Comment by kanchan-bluebash** [comment]
@darmenise It works correctly on all devices and on production as well. We can close this issue.
