### ISSUE TITLE
Authorization statement should be i18n

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#113]
Currently, the default authorization statement seems to be in Italian only:

![image](https://user-images.githubusercontent.com/794154/113572859-4cb1c680-9619-11eb-887b-e6d69ebb9892.png)

It should instead be internationalized based on the domain used for the registration. 

.it => Italian
.org => English

**Comment by OlivierJM** [comment]
Hi @darmenise How can I help on this ?

**Comment by darmenise** [comment]
Hi @OlivierJM! 
The authorization statement, according to EU law, should be at the bottom of every CV. 

PubliCV has currently 2 versions: publicv.it (italian) and publicv.org (international)

I took care of the Italian version, but we need to make sure that when a user generates their CV through the international platform (hence, when the app locale is set to `:en`), the following default statement should appear instead:

"I hereby authorize the use of my personal data in accordance to the GDPR 679/16 – European regulation on the protection of personal data"

Probably, in a PR for this, you'd simply need to change line 119 of this locale file: `config/locales/app.en.yml:119` and then test it :)

Wanna give it a go?

Also, please note that this project is aimed at having a positive impact on employment by "cutting the middlemen out". You can learn more both on PubliCV [homepage](https://publicv.org) and [here](https://pledgeviewer.eu/pledge/initiative/659).

So, really, _any_ help is greatly appreciated 😄

**Comment by OlivierJM** [comment]
Hi @darmenise Thanks a lot for the explanation, I will give it a go and I will ping you once am done, probably after my work hours today.

**Comment by OlivierJM** [comment]
Hi @darmenise I made the change, but I want to make sure I make a proper setup so that I can test that properly. 

Quick question the tests should be written in cv_test.rb right?

**Comment by darmenise** [comment]
It depends 🤔  I'm thinking that for what is basically a translation fix it may not be needed, please create the PR so that I can review it and point you in the right direction :)

**Comment by ValerioVillani** [comment]
@duarme this is the most used sentence for authorization:

"I hereby authorize the use and processing of My personal data in compliance with the applicable laws and regulations."
