### ISSUE TITLE
The user should be able to choose wether to publish their last name on the HTML version

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#12]
The online publiCV is a subset of the full-PDF-exportable one, the user should be able to decide which info to publish and which not (such as his/her last name).

**Comment by vishal-bluebash** [comment]
TODO:

1) On PDF user's full name should Appear
2) For live, the user should have the ability to choose whether to show the last name or not

**Comment by rahul-bluebash** [comment]
@vishal-bluebash PR for this - https://github.com/publicv-org/publicv/pull/32

**Comment by rahul-bluebash** [comment]
@darmenise This has been merged to production.
