### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#135]
As soon as the traffic grew even a little, we were running into out-of-memory errors. So I updated the dyno from 1GB RAM to 2.5GM RAM, but we are still running into the same errors regardless of having more than doubled the RAM memory. See Heroku:

![image](https://user-images.githubusercontent.com/794154/116845600-88bf5380-abe6-11eb-90ec-dfebe24b45b1.png)

It's now clear that we have some memory leak that needs fixing. IMHO one good way to fix this is to install the New Relic add-on (as we did for Corsidia), and a good place to start looking is the map functionality because I'm afraid it currently has to load all of the CVs for each call. This needs to be optimized.

**Comment by darmenise** [comment]
Please note that I partially solved a similar problem on Corsidia using pluck to load the minimum necessary data to show the markers on the map, but we still need clustering. If you need access or clarifications about the current solution on Corsidia, feel free to ask me!

**Comment by vishal-bluebash** [comment]
@darmenise new search scheme is deployed on production, for this, we have upgraded to Postgres 13.6 and setup Heroku CI

**Comment by vishal-bluebash** [comment]
Its deployed on production, so closing it
