### ISSUE TITLE
APP Crashing due to memory leak

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#158]
By using materialized views @vishal-bluebash was recently able to significantly improve the memory usage of PubliCV. 

Problem is that, despite this, we are still hitting out-of-memory errors:

<img width="1193" alt="CleanShot 2021-07-04 at 14 03 52@2x" src="https://user-images.githubusercontent.com/794154/124382554-ba30ca00-dcd0-11eb-847a-cee89635fba4.png">

**Comment by darmenise** [comment]
@vishal-bluebash This morning the app crashed, it seems related to the memory leak:

![CleanShot 2021-08-02 at 09 54 38](https://user-images.githubusercontent.com/794154/127824718-909a083f-5d97-48e9-a2d3-b3ee79f7d9ea.png)

I restarted the server and we're back online. We also need some sort of notification when this happens, there is a Slack bot that does that.

**Comment by darmenise** [comment]
We'd also need an error page because, instead, the Heroku error page was showing.

**Comment by darmenise** [comment]
I had to upgrade the server to a Performance Dyno with 2.5GB RAM ($250/month) as a temporary solution 🤞

**Comment by darmenise** [comment]
For now the App isn't crashing anymore, but still using an unreasonable amount of RAM:
![CleanShot 2021-08-02 at 17 48 51](https://user-images.githubusercontent.com/794154/127888895-845058a9-f641-49f1-b84c-25a7d1173cc6.png)

**Comment by vishal-bluebash** [comment]
@darmenise okay we are very close to finish project - map improvements

**Comment by darmenise** [comment]
I'm reopening this because I still see this region on loading the homepage:

![CleanShot 2021-08-07 at 11 16 05](https://user-images.githubusercontent.com/794154/128595439-71a3f00d-4449-41e2-a415-255c28bfbe6c.png)

I should instead be seeing Italy, or, if the problem is accuracy, another solution would be to zoom significantly out and show the whole world. With map clusters, would that be a problem now from a memory perspective?
