### ISSUE TITLE
Notifications for contact messages

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#159]
Since emails are never 100% reliable, users must be able to see the received messages in their back-end too.

After signing up, the user must see a button with the number of new messages on the top bar (same as what currently happens on Corsidia, also the usual social networks are a good reference) by clicking on that button a view with all messages should open. There the user must be able to read all of the messages, when a message is accessed, its status changes from "new" to "open", and it stops being counted among the "new messages".

It's also important to create a super-admin view for us to analyze messages and come up with the best anti-spam keywords, see #160

**Comment by bb-varun** [comment]
User Story:
When I login and click on contacts I should be able to see number of new contact messages in the list.

Problem:
As a user when I login to my account and search for the people who contacted me I am unable to identify new contacts and mails that I received.

Solution:
As a user I want a notification button stating number of new messages received , clicking on which I will be able to view all the contacts . Also it should have a button stating it is New, after opening New should change to Open and number from notification button should decrease.

Note: No need to create separate PR for this issue. You can create a child branch of this issue and merge with PR of #204.

- [ ] Notification Button created?
- [ ] Numbers increasing and decreasing on notification button when a new message received or a 
       message is read respectively?
- [ ] Status changing from New to Open?
- [ ] Created a child branch for the same in PR #204?
- [ ] Created a demo video when issue is solved on local host?
- [ ] Added issue number and appropriate labels in the PR?
- [ ] Code documented/Commented?
