### ISSUE TITLE
Authorization gem

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#161]
Once @vishal-bluebash decides on the authorization gem we'll use, we need to apply it to all the main controllers.

Pundit is simpler, but my arguments for CanCanCan are:

- arguably better maintained (see contribution graphs, issues and PRs).
- same as Corsidia (so that code we write is more reusable among the 2 projects).
- the maintainer is also a PubliCV and Corsidia contributor (he helped with the first release of both platforms and still is helping when we have issues).

**Comment by vishal-bluebash** [comment]
@darmenise looking at all the facts I have decided to use CanCanCan
