### ISSUE TITLE
Trying to access a CV results in a redirect to the homepage!

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#168]
Currently, when trying to access a cv through the cv path, for instance `https://publicv.org/cv/slug` it redirects back to the homepage. Each published CVs neest to be accessible from both the subdomain `slug.publicv.org` and the path `publicv.org/cv/slug`. We need to fix this asap otherwise all search results are currently useless.

This applies, of course, only to Cv with `published == true`.

Please also add a regression test so that this will never happen again.

**Comment by darmenise** [comment]
@vishal-bluebash I know you hotfixed this, can we close it or it's better to wait for a regression test?

**Comment by vishal-bluebash** [comment]
@darmenise we need to wait on this , we should have better test coverage on this
