### ISSUE TITLE
Contact form is flaky, we need a better UX and we need to save messages into the backend too.

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#173]
**User Story**
As a Company user, I am trying to contact a candidate of interest.

**Problems**
- The reset button and the Google reCaptcha icon are too close and covering the send button.
- I am not sure that my message gets received because, after send, I see no success message.

**Suggested Solution**
- We need to free the send button from clutter.
- We need to make sure that the message gets sent and, if so, show a success message 

⚠️ the above solutions need to be deployed asap, then we can also:

- We need to make save the message to the backend because emails can always fail.
- In order to improve deliverability, we need a spam filter to avoid sending spam through our email service. Please note that we already developed something similar for Corsidia, so there's no need to "reinvent the wheel".
- In order to detect spam, we should add a "website URL" to the form, so that the Company can use that specific form if they need to add the company website or a link to the job offer. Every link added to the content will be considered spam. We shouldn't send clickable links through email to both protect our users and our spam score.

**I tried to contact myself but couldn't receive the email.
Can we confirm that the messages do get sent, and received?**

Also, we don't need a "Reset" button, especially not near the "Send" button.
We can also get rid of the "reCAPTCHA" icon, as we did on Corsidia, by adding a "Protected by Google reCAPTCHA" notice at the end of the form.

![CleanShot 2021-08-03 at 17 23 59@2x](https://user-images.githubusercontent.com/794154/128042246-bbc7683b-3c1e-4578-ad33-f0a01454d601.png)

This depends on #174

**Comment by darmenise** [comment]
Instead of a "Reset" button we should have the usual "X" on the top right corner to close the form.
