### ISSUE TITLE
website field is not getting updated

### ISSUE THREAD

**Issue by bb-varun** [publicv-org/publicv#181]
User Story
As a user, I am trying to update the CV and entering the website address in the "Experience" section to add my experience.

Problem:
I am not able to add the website address if HTTP or https is not added before the website link. 

Suggested Solution:
Recheck & update the existing validations so that I can add the website link easily without adding the http/https.
![Screenshot issue](https://user-images.githubusercontent.com/87966762/128476902-7a14cc3b-60a8-445a-9e7f-b9a745b2dae4.png)

**Comment by darmenise** [comment]
Yes, a `before_validation` callback should do the trick.

Something like:

```ruby
before_validation :check_website_url

def check_website_url
  self.website_url = "https://#{website_url}" unless website_url.starts_with?('http')
end
```

👆 this can be improved, of course.

**Comment by vishal-bluebash** [comment]
@darmenise some times if the website has no SSL, then appending HTTPS could cause problems. what about accepting HTTP and https both URLs?

**Comment by darmenise** [comment]
Ok, then something like this:

```ruby
before_validation :check_website_url

def check_website_url
  self.website_url = website_url.squish.strip.downcase # removes spaces and makes it downcased
  self.website_url = "http://#{website_url}" unless website_url.start_with?('http') # adds protocol if missing
end
```

So that the website will take care of the possible redirect to https, ok?
