### ISSUE TITLE
The button to "Hire candidate" stopped working

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#19]
For some reason, the button to send a message to a candidate isn't working anymore. Maybe something broke at JS level, but this is critical to fix.

**Comment by darmenise** [comment]
@rahul-bluebash please note that we should be using the `gem 'recaptcha'` which is the same we're using for Corsidia or similar. Don't reinvent the wheel: if you need to look at Corsidia's code to replicate this functionality, you can! :)

**Comment by rahul-bluebash** [comment]
@darmenise Sure, I will do that.
