### ISSUE TITLE
Map centering in SERP

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#197]
As a company, I'm looking for candidates in my area, so I search, for instance, "Milan".
But what I see on the map is the center of India:
![CleanShot 2021-08-19 at 13 20 22](https://user-images.githubusercontent.com/794154/130060369-999da20e-42e2-402c-97a7-c4858a37a0e5.png)

Instead, I should see this:

![CleanShot 2021-08-19 at 13 22 12](https://user-images.githubusercontent.com/794154/130060438-0cbf941f-af4d-4e71-8573-0617f8e9b5f1.png)

**Possible solutions**
1. It used to work before updating the main map, it's possible that we simply need to geolocate the first result and then use their coordinates to center the map in the SERPs.
2. Another solution would be to center the map using the user coordinates (the same that we use to center the homepage).

**Comment by vishal-bluebash** [comment]
My vote goes to first solutions, because with second we can get a situation where I will see no result on map but result on left hand side

**Comment by darmenise** [comment]
I agree, but what if the first result isn't geocoded? We could fall back on the next result, or on the user location (if no result is geocoded).

**Comment by vishal-bluebash** [comment]
@darmenise Yes we should do that
