### ISSUE TITLE
 Flag inappropriate content functionality

### ISSUE THREAD

**Issue by vishal-bluebash** [publicv-org/publicv#206]
User Story:
As a job provider I should be able to flag the inappropriate content.

Problem:
I see an inappropriate content and review it and I cannot mark it as flag .

Solution:
I see an inappropriate content and review it and I want to mark it as a flag. After receiving certain number of flags in a short period of time (only by registered users) the content should get unpublished by default.

- [x] Jobseeker able to flag the content?
- [x] Flags visible to Jobseeker?
- [x] Created the PR and assigned the label?
- [x] Added issue no in PR?
- [x] Commented /Documented the Code?

**Comment by darmenise** [comment]
I think that not only as a job provider, but also as a regular user you should be able to flag inappropriate content. The primary goal is to protect PubliCV from people publishing inappropriate images.
