### ISSUE TITLE
Subdomain for CV should be downcase

### ISSUE THREAD

**Issue by vishal-bluebash** [publicv-org/publicv#21]
User story: As a user when I signup with the domain and domain has capital letters into it. Once Cv is published I am not able to access my CV on a subdomain for example

Subdomain added on Signup - Vishal-Garg
URL generated for publicv - Vishal-Garg.publicv.org

Problem:
Domain names considered  as downcase always so when we type `Vishal-Garg.publicv.org` it becomes `vishal-garg.publicv.org` and Application is not able to find CV for vishal-garg subdomain

Solution:
Make sure whenever we save any subdomain downcases it

**Comment by rahul-bluebash** [comment]
@vishal-bluebash Here is the PR for this - https://github.com/publicv-org/publicv/pull/23

**Comment by darmenise** [comment]
A `before_validation :downcase_subdomain` filter would do :)
There's also a commented TODO for subdomain format validation in the User model.

**Comment by darmenise** [comment]
It would be better to use a subdomain validator such as this one:

```ruby
# app/validators/subdomain_validator.rb
class SubdomainValidator < ActiveModel::EachValidator
  def validate_each(object, attribute, value)
    return if value.blank?

    reserved_names = %w[www bounces images ftp mail pop smtp admin user ssl sftp verify tracking]
    reserved_names = options[:reserved] if options[:reserved]
    object.errors[attribute] << 'cannot be a reserved name' if reserved_names.include?(value)
    check_subdomain_format(object.errors[attribute], value)
  end

  def check_subdomain_format(errors, value)
    errors << I18n.t('errors.subdomain.length') unless value.length.between?(3, 63)
    errors << I18n.t('errors.subdomain.dashes') unless value.match?(/^[^-].*[^-]$/i)
    errors << I18n.t('errors.subdomain.format') unless value.match?(/^[a-z0-9\-]*$/) # <= only downcase is accepted
  end
end

# Use as follows
# # In model
# validates  :subdomain, :presence   => true,
#                        :uniqueness => true,
#                        :subdomain  => true
#
# # Specifying own reserved names
# validates  :subdomain, :presence   => true,
#                        :uniqueness => true,
#                        :subdomain  => { :reserved => %w(foo bar) }
```
