### ISSUE TITLE
It's hard to sign up when you pick an already registered subdomain

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#219]
As a new user, I want to sign up.
If I pick an already registered subdomain the error is confusing.
Furthermore, the concept of "subdomain" itself is confusing to most users.

**Proposed solution**

We should automatically generate a unique subdomain, then give the user the option to change it. Like Twitter does with its usernames. Furthermore, people may misspell their subdomain the first time!

@ValerioVillani

**Comment by vishal-bluebash** [comment]
@duarme Yes, I think its a good idea, let's do that

**Comment by duarme** [comment]
@kanchan-bluebash Let's keep it as simple as possible. Something like:

```
def slug_candidates
    [
      :first_name, # we try with the name first
      :frist_name_plus_progressive_number # then we attach the first number that's not already taken
    ]
  end
  ```
  
  So, for instance, for me it will try:
 

1. `duccio`
3. `duccio1`
3. `duccio2`

...and so on until one is available.

The important part is that the user will be able to customize their username later, as much as they want.

And if you see `kanchan33` as your username, you'll more likely customize it 😉
