### ISSUE TITLE
Flash message

### ISSUE THREAD

**Issue by bb-varun** [publicv-org/publicv#224]
User Story:
 After signing up I am given a unique subdomain automatically.
 
 Problem:
 As a user, I don't like my username, so I want to change it but I cannot find any option from where to update it.
 
 Suggested Solution:
 A flash message should be there which tells "You can update your username from settings".Hence users can check in settings, and update their username
 
![Screenshot (4)](https://user-images.githubusercontent.com/87966762/136158813-251a56de-444c-4abb-8f70-d0e2be7f1dcf.png)

**Comment by ValerioVillani** [comment]
@bb-varun Hi Varun! Can the solution be the one I proposed in issue #257 ?

**Comment by bb-nikita** [comment]
Hi @ValerioVillani . Yes, for sure we will be working on it.

**Comment by ValerioVillani** [comment]
@bb-nikita Hi Nikita! Thank You.

**Comment by duarme** [comment]
solved with #257

**Comment by duarme** [comment]
We need to close this in order to solve #356

**Comment by bb-nikita** [comment]
https://github.com/publicv-org/publicv/pull/362 is solving both https://github.com/publicv-org/publicv/issues/356. See PR https://github.com/publicv-org/publicv/pull/229 partially 

@duarme @ValerioVillani its ready for staging QA please check this
