### ISSUE TITLE
Setup GTM for site 

### ISSUE THREAD

**Issue by vishal-bluebash** [publicv-org/publicv#24]

**Comment by darmenise** [comment]
Oh, Google Tag Manager! (It took me a while XD) 
Never used it before, for what do we need it?

**Comment by vishal-bluebash** [comment]
@darmenise Once we integrate GTM we can add/remove any on-page script from its dashboard like GA, Facebook pixel, etc.


https://enventyspartners.com/blog/what-is-gtm-what-is-it-for-and-how-do-i-use-it-in-my-business/

**Comment by darmenise** [comment]
We are not tracking
