### ISSUE TITLE
App Optimization.

### ISSUE THREAD

**Issue by ritik-bluebash** [publicv-org/publicv#252]
**Worked on optimising the app and reducing response time of the app.** 
1. Updated the puma configuration to shift the load from one worked to two workers with worker timeout of 15 seconds.
2. Loaded the data for homepage map from serializer and filtered that data in JS and removed the filtering at the backend.
3. Updated the query for loading featured CVs on homepage so that there are not much queries while loading the homepage. Loaded the required data from SQL and reduced the number of queries.
4. Loaded the homepage using cache with an expiry of 4 hours. (Seperate for .it and .org).
5. Loaded the CV's show page through cache. 
 5.1 Added separate cache keys for preview page and edit page (Seperate for .it and .org).
 5.2 Updated the CV on updating the anything from experience, education and language so that key also gets updated and the user gets to the see the updated CV and not cached as key is dependent on updated_at of CV.
 5.3 Added test coverage for same.
6. Added rack timeout gem so that the app doesnt get timeout and thus app doesnt get crashed.
7. Added the UI fixes for featured CVs on homepage.
8. Added rack attack gem for throttling requests on homepage, CVs show page, searches page and for CVs subdomain URL page as well.

**Comment by vishal-bluebash** [comment]
@ritik-bluebash This looks good

**Comment by bb-nikita** [comment]
Hi @duarme, All of this is done and it's on production.
Thank You.
