### ISSUE TITLE
Home page - Scroll to zoom in/out the map positioning

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#255]
Home page map:

- Right now the "Scroll to zoom in/out the map" sentence is positioned lower left.
This makes the sentence a bit hard to see.

![Scroll to zoom map is not visible](https://user-images.githubusercontent.com/90318732/145010707-1a649f11-2ef6-4cd2-918b-4c61f253471a.PNG)

Possible solution:

How about changing its position?

![Possible solution scroll](https://user-images.githubusercontent.com/90318732/145010828-4e1a2501-e044-4ec9-bab8-3a339b059446.PNG)

**Comment by duarme** [comment]
Even better, if possible, would be with a gray overlay, like Google Maps does:

https://user-images.githubusercontent.com/794154/145087493-4de5a127-6c5c-432a-85da-cba6a812a016.mp4

But with centered text would be even better!

**Comment by ValerioVillani** [comment]
@duarme I do Agree!

**Comment by duarme** [comment]
Please @ritik-bluebash remember to add the linked PR when you add the PR ready label, thanks! (I did it now)

**Comment by vishal-bluebash** [comment]
@duarme If we link PR, there is a downside when we merge PR it will close issue automatically, This feature is really useful when we use Heroku review apps. As we are not using that we need ticket until we verify it on prod and close it manually

**Comment by duarme** [comment]
@vishal-bluebash  Ok, I understand. Then, in your experience, what would be the best way to easily find the PR for an issue when they aren't linked? I ask this because it wasn't easy to locate some of the PR for the "PR ready" labeled issues. Should we always add the issue code into the PR title? Or do you have a better idea?

**Comment by vishal-bluebash** [comment]
@duarme On Issue we need to add One comment with PR link when we mark it as ready for review - we add label currently 

Rest I will get some time to clarify all development process in wiki, I am working on that with @bb-nikita

**Comment by vishal-bluebash** [comment]
@ValerioVillani its on production, have you checked it, it is solving purpose for now, Later we can work on UX of it

**Comment by ValerioVillani** [comment]
@vishal-bluebash Ok perfect! That's why i marked it as priority minor. 

Should i close this one and open a new one when we will be ready for Ux improvement?

**Comment by vishal-bluebash** [comment]
@ValerioVillani Yes @ValerioVillani good to have new ticket and close this one
