### ISSUE TITLE
Home page - "Your CV" Button (It's not intuitive)

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#256]
Home page - "Your CV" Button (It's not intuitive)

- Right now we have 2 different actions linked to the "Your CV" Button.

![Cattura](https://user-images.githubusercontent.com/90318732/145014934-2831c5de-4d3d-4e1b-8821-b7c5585b8365.PNG)

Since I need to click the "Your CV" button to both login or create a new account, I realised that this makes our home not intuitive both for new users and existing accounts.

![Your CV button](https://user-images.githubusercontent.com/90318732/145012027-f4e313e5-5d07-4e48-a7b7-06eae53ee1ef.PNG)

Possible solutions:
How about reshaping that bar by dividing the "Your CV" Button into 2 different buttons like "Create Your CV"  and "Login to Your CV".

In this way:
- "Create your CV" button could be more intuitive for new users.
- "Login to Your CV" button will be perfect for users already on the platform.

**Comment by ValerioVillani** [comment]
Mm. Good idea but to me "add" looks like a bit that "If you have your cv, you can add it".
"Create" instead gives me more the idea of "write from 0 your Cv with me".
But idk honestly, lets listen other opinions.

**Comment by duarme** [comment]
@bb-nikita this can be now finished.

Instead of having the "Your CV" button with 2 nested buttons inside, we simply need the 2 buttons:

"Create your CV" and "Edit your CV" side by side on the desktop view, and one above the other on the mobile view.

**Comment by ritik-bluebash** [comment]
PR link :- #286
