### ISSUE TITLE
Editing Your CV/Profile - Reminder to publish your CV / Once you publish your CV - copies not clear 

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#263]
I realized that the Copy we are using to explain that the CV has to be published in order to be searched by the recruiters is a bit too long and not clear. (Both for Italian and English Version)

![Cattura 2](https://user-images.githubusercontent.com/90318732/146212922-84a91f14-b97e-48d0-bcd0-9b32a0fd9a7e.PNG)

I Would suggest (English version):

remember to publish your resume (Publish button) to make it visible to recruiters!

I would suggest (Italian Version):

Ricorda di pubblicare il tuo curriculum (Publish button) per renderlo visible ai selezionatori!

once you Publish It:

![Cattura](https://user-images.githubusercontent.com/90318732/146213224-b1c95289-d081-444c-b593-a23c94db0207.PNG)

I Would suggest (English version):

Your CV is now published and visible to recruiters!
We wish you the best of luck in your next interviews!

I would suggest (Italian Version)

Il tuo CV è ora pubblico e visible ai selezionatori!
In bocca al lupo per i tuoi prossimi colloqui!

**Comment by duarme** [comment]
Probably it's better to make them published by default? 🤔

**Comment by ValerioVillani** [comment]
@duarme Can I create an issue to make the CV published by default?

**Comment by ValerioVillani** [comment]
reformulated with #340
