### ISSUE TITLE
[Customer's Issue reported] Users are not answering requests from our contact form

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#266]
Our Top Client has shared with us that candidates are not answering their requests made by our contact form. 

I would suggest to:

- Ensure that users actually receive our email.
- Ensure that our email won't go in SPAM.
- Try to use The Corsidia's Back-end for messages (users receive messages even if they don't receive them by email)

Other opinions?

**Comment by duarme** [comment]
Hi @ValerioVillani currently they have a backend where they can see all the received messages, try to login and go to https://publicv.it/messages, you should see something like this:

![CleanShot 2021-12-16 at 15 24 31@2x](https://user-images.githubusercontent.com/794154/146399641-f98e3c3d-0430-4d34-babb-31eac63d45ff.png)

One other problem could be that some CVs are old, or users cannot access them anymore. First of all @bb-nikita, please make sure that we are sending email notifications correctly. How can we improve our deliverability?

**Comment by duarme** [comment]
We run a test and it turned out that all is working well. We need to think about how to improve engagement.
