### ISSUE TITLE
Devise translations are missing

### ISSUE THREAD

**Issue by rahul-bluebash** [publicv-org/publicv#27]
![org-transalation-missing](https://user-images.githubusercontent.com/43989104/81210707-e464fa00-8fef-11ea-9b65-35f8e32ec845.png)
![button-translations](https://user-images.githubusercontent.com/43989104/81210713-e62ebd80-8fef-11ea-99ae-838aa2b26960.png)

**Comment by vishal-bluebash** [comment]
@darmenise I have merged but you need to add a translation for .it

https://github.com/publicv-org/publicv/pull/29
