### ISSUE TITLE
Profile/CV Creation - Make mandatory some Boxes?

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#270]
At the moment the only mandatory box to fill is " First Name " and " Last Name"

Since the Date of Bird and Current City are crucial factors for recruiters, how can we share the importance of filling these boxes with correct Infos?

I've seen a lot of times that DoB and Email are mandatory. (Probably in contrast with GDPR)

Can we set them mandatory?

Or maybe remember that filling all boxes with correct Infos increase the chance of finding a new job.

**Comment by ValerioVillani** [comment]
@duarme What do you think?

**Comment by duarme** [comment]
For platform sign-up I think we are required to check the age of the user. So we should ask the DoB and make at least the year mandatory. We should add this field to the very first sign-up form.
