### ISSUE TITLE
[CV Format] - Modify "Skills" in "Skills and Business Areas"

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#271]
Since that Industry and Specialties play a crucial role in job seeking.

I would suggest modifying the "Skills" area into "Skills and Business areas". (You can find the ratio in issue #267 )

![From Skills to Skills and Business Areas](https://user-images.githubusercontent.com/90318732/146545867-fbcd31ea-c5b5-4ee6-8994-828c9ad2c424.PNG)

For Italian version: "Competenze e settori".

**Comment by duarme** [comment]
We need to think about how this would impact the Skills knowledge graph. First of all, we should define what we expect from it, we'll have a discussion about that asap :)

**Comment by ValerioVillani** [comment]
@duarme 
I can't help from a technical point of view.
But from a recruiter perspective, The Industry (sector, business areas, specialities) is as important as skills.
As u said we need to understand if it can be technically good.
