### ISSUE TITLE
[CV Format] Make uneditable "Authorization Statement" 

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#272]
Right now users have the possibility to modify the "Authorization Statement".

![Shouldn't be editable](https://user-images.githubusercontent.com/90318732/146546858-f1e0a7e4-93e5-4918-bd86-3aa54c6417bf.PNG)

It can lead to problems.

Possible solution:

- Make it uneditable

**Comment by duarme** [comment]
What problems do you think it can lead to? 🤔 Also, this should probably be printed along with the PDF version only, right?

**Comment by ValerioVillani** [comment]
@duarme 
Yes, It definitely has to be on pdf.
The main constraint can be that someone accidentally deletes the sentence and sends around CVs with our logo with no Authorization sentence (It can lead to some bad reputation, isn't it?).
And another thing is.. why it is editable?

**Comment by duarme** [comment]
Ok, I think you're right, we should have a standard version for each language. For Italian, it stays the same, while for English please paste here your preferred version. Then this notice will appear under each online published CV, and under each downloaded PDF. Right?

**Comment by duarme** [comment]
Please @ritik-bluebash link the PR :)
