### ISSUE TITLE
Fix heroku deployment

### ISSUE THREAD

**Issue by vishal-bluebash** [publicv-org/publicv#278]
https://devcenter.heroku.com/changelog-items/2306

Ruby apps now default to Node version 16.13.1 and Yarn version 1.22.17

**Comment by vishal-bluebash** [comment]
@bb-nikita @ritik-bluebash Let's test application staging to make sure everything is fine as expected (UI wise)

**Comment by ValerioVillani** [comment]
@vishal-bluebash can we close this now?

**Comment by vishal-bluebash** [comment]
Yes @ValerioVillani I am closing it, its done
