### ISSUE TITLE
[Mobile Version] - Home page Text Bug (iPhone)

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#279]
Hi guys! I've found that in the mobile version (iPhone) there's an interpenetration between the menu and the text.

![image_6487327 (15)](https://user-images.githubusercontent.com/90318732/147100316-d88501c6-d7e2-4550-aeec-ff9744387acc.JPG)

Possible solution:

Can be nice if we make the text smaller

For example:

![Cattura](https://user-images.githubusercontent.com/90318732/147100475-195eabca-02fa-4ca7-9cf0-09bc08d7bb9c.PNG)

**Comment by duarme** [comment]
@ritik-bluebash I think this should already be solved, I made the text smaller using a `small` tag. Should be on the main branch.

**Comment by ritik-bluebash** [comment]
Yes @duarme 
We can close. Also if any change will be required in size of `your digital CV`, then it can be updated in #280.
