### ISSUE TITLE
[Mobile Version] - Make "Menu Button" more intuitive and user friendly

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#280]
Right now, the menu button (mobile version) is okay but in order to make it more intuitive and user friendly to our users, I would suggest adding the "Menu" Text. 

A lot of companies do that for their mobile version:

![Menu](https://user-images.githubusercontent.com/90318732/147101429-740d3deb-3361-4aaf-92d9-15cdba59fea9.PNG)

Possible solution:

Make the text smaller and add here the "menu text" (I would actually make everything smaller and cleaner)

![Menu button PubliCV](https://user-images.githubusercontent.com/90318732/147101523-752cec75-6075-460a-a545-c9e201b1f083.PNG)

**Comment by ritik-bluebash** [comment]
Hello @ValerioVillani
I have tried adding the menu text near hamburger icon. and it looks like this.
![Screenshot from 2021-12-27 12-52-54](https://user-images.githubusercontent.com/80153678/147448389-8fa3a0ef-e801-48f0-a9f5-39b9d36212bf.png)

Even if we make burger icon small, there is not much space left for menu text. 
What we can do is we can hide **your digital Cv** label on mobile and keep Menu label.

Checked on other website as well, they only had logo in their mobile navbar with menu text.

**Comment by ValerioVillani** [comment]
@ritik-bluebash 

Hi Ritik, good job!

As you said one potential solution can be hide "your digital cv" label.

The other one is to make the logo and "your digital cv" label smaller.

Lets try both! And then we'll decide the best one.

**Comment by ritik-bluebash** [comment]
@ValerioVillani 
![Screenshot from 2021-12-27 13-45-20](https://user-images.githubusercontent.com/80153678/147450727-1f2fba14-4640-4ec8-8672-8048085c88e3.png)
![Screenshot from 2021-12-27 13-44-06](https://user-images.githubusercontent.com/80153678/147450731-cac7d0f1-aed0-435e-af44-8cf60b305299.png)

Please check these two solutions and let me know the better one or any other change required.

**Comment by ValerioVillani** [comment]
At the moment I Think that Option number 2 is more user friendly.
I would suggest instead of "MENU", try to write "Menu" (you can make the character even smaller and increase the distance between Menu and Hamburger Icon).
Then you can make "your digital CV" a bit smaller.
Let's try how it looks like. :)

**Comment by duarme** [comment]
For now let's keep it this way, for the future, here are a few things to consider: https://uxplanet.org/the-ultimate-guide-to-the-hamburger-menu-and-its-alternatives-e2da8dc7f1db 

I know @ValerioVillani is concerned with intuitiveness, one other way to improve it is to add CTAs on the homepage, which are already present. See, for instance: 

<img width="332" alt="CleanShot 2021-12-27 at 09 32 58@2x" src="https://user-images.githubusercontent.com/794154/147457941-4c782f31-8b63-43c3-b485-b8408f847bbb.png">

Anyway, adding `Menu 🍔` on the top right, I think is a good call.

**Comment by ritik-bluebash** [comment]
> At the moment I Think that Option number 2 is more user friendly. I would suggest instead of "MENU", try to write "Menu" (you can make the character even smaller and increase the distance between Menu and Hamburger Icon). Then you can make "your digital CV" a bit smaller. Let's try how it looks like. :)


![Screenshot from 2021-12-27 15-43-40](https://user-images.githubusercontent.com/80153678/147461767-d45c86b7-a76e-4239-b14d-fa5fbcbad98a.png)
@ValerioVillani Check this view for mobile.

**Comment by ValerioVillani** [comment]
I love it! 

@duarme what do you think with the last options?
