### ISSUE TITLE
Search Bar and Results - the search tab doesn't show you what is being sought

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#288]
Once you perform research, the search tab doesn't show you what is being sought.

https://user-images.githubusercontent.com/90318732/147462022-d7a2ac94-3e6d-4bb6-acc8-11c0dce5bca9.mp4

I think it can greatly improve the user experience, highlight the keywords you are looking for.

possible solutions:

1) leave the sentence as it is written in the search bar. (LinkedIn Example).

![Cattura](https://user-images.githubusercontent.com/90318732/147461257-67891626-acc4-4430-92f7-efb84e8bd820.PNG)

**Comment by ValerioVillani** [comment]
We should do the same for the mobile version:

![mobile map view research show what u searched](https://user-images.githubusercontent.com/90318732/147462925-ac9c841a-76d0-46d3-9377-94489ee09420.PNG)

**Comment by vishal-bluebash** [comment]
@bb-nikita @ritik-bluebash  Let's fix the issue first, searched term should be retained by search field similar to LinkedIn. 


@ValerioVillani Later we can do round of UI/UX improvement of pages so we can experience

**Comment by ritik-bluebash** [comment]
PR for issue is here:  #290
