### ISSUE TITLE
Edit Button Bug - Edit Personal Image

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#305]
From the last update, I've found a bug:

The Edit Button is too far from the Personal Image

![Edit button too far from picture](https://user-images.githubusercontent.com/90318732/148267388-1c6e251a-7f3e-44c3-9a35-3d1a7d732abd.PNG)

**Comment by ritik-bluebash** [comment]
PR link: #307

**Comment by bb-nikita** [comment]
Deployed to production
