### ISSUE TITLE
Icon Reduction - Text Overlapping bug

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#312]
There's a Bug in the text when you reduce YouCV page Dimensions.

It overlaps with icons:

![Icon Reduction Bar Bug](https://user-images.githubusercontent.com/90318732/148641130-1bad012d-d0c3-47f6-a8ee-78fee1618c4d.PNG)

**Comment by ritik-bluebash** [comment]
PR link: #317
