### ISSUE TITLE
Anti-abuse measures: now everyone can publish a picture without having to confirm their account

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#33]
We should publish pictures of confirmed users only.

It could either go like this:

1. confirm
2. upload

Or like this:

1. upload but the image is not showing and there's a message telling you to confirm before
2. confirm
3. now the image is live

**Comment by bb-varun** [comment]
User Story:
As a user, I want to  update my a CV and upload my Profile Picture on my CV.

Problem:
As of now I can upload a profile picture without having to confirm the account.

Solution:
I should only be able to update my profile picture if I verify my email. This can be done in two ways:
 1. I upload my picture and  it gives me verification link to confirm and upload.
 2. I upload the image but it is not visible and there is a message asking me to confirm and once I 
     confirm the image is live.

- [ ] Verified the account before uploading the picture?
- [ ] Created the PR and added the labels?
- [ ] Added the issue number in PR? 
- [ ] Commented/Documented the code?

**Comment by vishal-bluebash** [comment]
I like solution (2) @darmenise what are your feedback?

**Comment by darmenise** [comment]
I agree. Problem is that one can still update offensive pictures by using a disposable email address. We'll probably need also a "flag and report" button. But we can develop it later.

**Comment by vishal-bluebash** [comment]
@darmenise we have separate card for it https://github.com/publicv-org/publicv/issues/206

**Comment by bb-varun** [comment]
We are already verifying the account when publishing the CV, so no need to validate while updating the image.
