### ISSUE TITLE
Character counter while typing

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#35]
It's frustrating when you hit the maximum length in the middle of a sentence. 
Also, the maximum length is actually the suggested length. So it would be better to:

1. allow longer content (let's say max 1000 chars)
2. put a character counter 
3. having the character counter to change color based on suggested length (it should be green around 250-300 chars).

**Comment by vishal-bluebash** [comment]
https://github.com/publicv-org/publicv/pull/45

**Comment by vishal-bluebash** [comment]
its deployed to production but we need some additional work

- Add counter into- Professional summary and goals
