### ISSUE TITLE
No obvious way to sign back in

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#36]
We currently provide an obvious CTA to sign up but there is none yet to sign in. 
There should be a clear login CTA for those that already signed up.

**Comment by rahul-bluebash** [comment]
@darmenise In footer we have login option but on header we don't, Do we want this option beside Create Your CV button like as mentioned in screenshot ?
![update-cv-link](https://user-images.githubusercontent.com/43989104/83322026-04e04700-a272-11ea-93d1-3d1bab5c4e5f.png)

**Comment by darmenise** [comment]
How about a dropdown menu? The button could be "Your CV" and then a popup with the two options:

- Sign up to create your profile and CVs
- Sign in to update your profile and CVs

"CVs" can be singular, "CV", for now. But we'll soon provide the option to manage more than one CV. 

So that we don't break the Jobseeker / Jobofferer duality.

**Comment by vishal-bluebash** [comment]
its deployed to production and reviewed
