### ISSUE TITLE
After the last merge the map-centering functionality based on the visitor IP broke

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#41]
On the homepage, the Map used to be roughly centered on the visitor position (based on their IP address). Now it's not happening anymore.

I'm sorry, I think I broke something during the last merge and deploy!
@rahul-bluebash Can you please restore this functionality?

**Comment by darmenise** [comment]
I think I know why: the base branch was set to `master` when it actually should be `develop`. I was expecting that the most advanced branch was `develop`, as it should be, when, in fact, it was `master`. So when I merged `develop` into master, I mistakenly took the project back a few commits. Now the base branch is set to `develop`, so it shouldn't happen anymore.

**Comment by rahul-bluebash** [comment]
Hi @darmenise I checked this, I think is not about the merge....on homepage, map is now showing last 4 recent CVs as we need to show candidates in markers too. This has been done for this issue:
https://github.com/publicv-org/publicv/issues/17

Let me know, if this is okay or we need to do some modifications.

**Comment by darmenise** [comment]
You're right, but the problem is the animation. It starts centered on the candidates but then moves away. See:

![Screen Recording 2020-06-03 at 20 36 50](https://user-images.githubusercontent.com/794154/83676066-61c55f80-a5da-11ea-97f5-ac63553e7a04.gif)

It should instead stay centered on the approximate IP location.

**Comment by vishal-bluebash** [comment]
@darmenise Here what Rahul is saying that according to logic to show 4 CV in the map it try to show all CV in 1 view that's why it moved like this see all 4 cv's. there is 1 cv in India which getting covered.   

I think we need to change logic instead of showing all 4 CV's what about logic to show all CV's around my location in X radius ?

**Comment by darmenise** [comment]
Yes, exactly. The radius can be large, let's say 500Km or so around the estimated location. But this way the shown CV would be more relevant to the user.
