### ISSUE TITLE
Landbot and Recaptcha covering the send message button on mobile

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#50]
When I click on "hire candidate"
Then the popup appears but both Landbot and Recaptcha are blocking the send button:

![image](https://user-images.githubusercontent.com/794154/84789033-18b8d680-aff0-11ea-8f08-f73e0f128361.png)

The Reset button is useless. We should only have one big SEND button in the middle:

![image](https://user-images.githubusercontent.com/794154/84789445-87962f80-aff0-11ea-82c2-e69ebe4243f7.png)

**Comment by rahul-bluebash** [comment]
@darmenise Currently, I can't see landbot on contact form. If we move the landbot position to left side of the contact form, does that work, if we need to show that ?
