### ISSUE TITLE
Recaptcha is not working!

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#69]
I tried to contact a candidate for a real job offer but the contact form was always returning error without explanation.
The first thing I did was to attach the model to the `verify_recaptcha` so that, at least, we know that the recaptcha as failed (see 3d59f24415c6101c165b92aa3b96717d60ff6b39). But when that happens, we still need to provide the challenge for the user so that he can prove he's not a bot and pass the challenge!

See docs: https://github.com/ambethia/recaptcha#examples

**Comment by darmenise** [comment]
We need to be careful with this because this kind of error doesn't throw any exception, so it's hard to detect on our part!

**Comment by rahul-bluebash** [comment]
Here is the PR for this : https://github.com/publicv-org/publicv/pull/70
