### ISSUE TITLE
Scrolling is not working for published CVs on home page

### ISSUE THREAD

**Issue by kanchan-bluebash** [publicv-org/publicv#92]
Only the latest published CV is shown on the main page. The other published CV cannot be scrolled. Maybe bootstrap carousel component used for sliding of the CVs is not working.

 ![scroll](https://user-images.githubusercontent.com/81285549/113475900-940f4a00-9495-11eb-84d1-599b33cfc30d.png)

**Comment by darmenise** [comment]
Also, the date shown is `created_at`, it would be better to show `updated_at`.

**Comment by darmenise** [comment]
@kanchan-bluebash  after the PR merge, the scroll is now working 🎉  but only for those 4 CVs rendered with the page.
How hard do you think it would be to have a continuous scroll with ajax? Does the current carousel support something like that?

**Comment by kanchan-bluebash** [comment]
@darmenise Carousel has been removed as it was not working due to the bootstrap and jquery versions incompatibility. I have added some custom classes for implementing scrolling . Also, I have checked for the continuous scrolling with the current fix. We could achieve this by using javascript events.
